### ISSUE TITLE
User Story: GitHub Action Deploy Workflow

### ISSUE THREAD

**Issue by csantiago132** [Kurocado-Studio/styleguide#29]
create a reusable composite action that can deploy a Dockerized app to Fly.io

```yaml
name: Deploy to Fly.io
description: Composite action to deploy Dockerized apps to Fly.io.
author: Carlos Santiago
inputs:
  fly_api_token:
    description: 'Fly.io API token used to authenticate deployment'
    required: true
  app_name:
    description: 'The name of the Fly.io application'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile used to build the image'
    required: false
    default: './Dockerfile'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Fly.io
      run: |
        echo "${{ inputs.fly_api_token }}" | fly auth token
      shell: bash

    - name: Build and push Docker image
      run: |
        docker build -t ${{ inputs.app_name }} -f ${{ inputs.dockerfile }} .
        fly deploy --remote-only --config ./fly.toml
      shell: bash
```

### Using the Reusable Composite Action in a Workflow
```yaml
name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # Trigger the action on push to main branch.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Fly.io
        uses: kurocado-studio/styleguide/.github/actions/deploy-to-flyio
        with:
          fly_api_token: ${{ secrets.FLY_API_TOKEN }}
          app_name: 'nestjs-shopify-app'
          dockerfile: './Dockerfile'
```

### Publishing the Action for Reuse in Other Repos

```yaml
steps:
  - name: Deploy to Fly.io
    uses: kurocado-studio/styleguide/.github/actions/deploy-to-flyio@main 
    with:
      fly_api_token: ${{ secrets.FLY_API_TOKEN }}
      app_name: 'APP_NAME'
```

# Acceptance Criteria

1.	Composite Action:
	•	A reusable composite action is created and stored at .github/actions/deploy-to-flyio/action.yml.
	•	The action accepts inputs for fly_api_token, app_name, and dockerfile.
	•	The action successfully logs into Fly.io, builds a Docker image, and deploys it to Fly.io.
2.	GitHub Workflow:
	•	The composite action is used in a GitHub workflow and triggers deployment upon push to the main branch.
3.	Environment Variables:
	•	Fly.io API token is securely passed via GitHub Secrets.
